FileVersion = 1

[Project]
Name = "quickjs-beef"
DefaultNamespace = "quickjs"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\qjs_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\qjs.lib"]
